language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sakemu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sakemu/docker-react npm run test